#!/bin/sh

# The GPLv2 License
#
#   Copyright (C) 2025 pyamsoft
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

readonly PROGRAM="update-geoblock"

_log() {
  _msg="$1"
  shift

  printf -- "[%s]: ${_msg}\n" "${PROGRAM}" "$@" || return 1

  unset _msg
  return 0
}

##
# Error Log
#
# Accepts arguments in the same format as printf
# $1 message
# $@ arguments
##
_elog() {
  _log "$@" 1>&2 || return 1
  return 0
}

main() {
  if [ "$(id -u)" -ne 0 ]; then
    _elog 'Must run as root.'
    return 1
  fi

  cd /usr/libexec/xtables-addons || {
    _elog 'Failed to cd into /usr/libexec/xtables-addons directory.'
    return 1
  }

  mkdir -p /usr/share/xt_geoip || {
    _elog 'Failed to make target /usr/share/xt_geoip directory.'
    return 1
  }

  chmod 755 /usr/share/xt_geoip || {
    _elog 'Failed to mark exec target /usr/share/xt_geoip directory.'
    return 1
  }

  # Download (will save as dbip-country-lite.csv)
  ./xt_geoip_dl || {
    _elog 'Failed to download latest geoip using xt_geoip_dl'
    return 1
  }

  ./xt_geoip_build -D /usr/share/xt_geoip dbip-country-lite.csv || {
    _elog 'Failed to convert CSV to GEO-IP using xt_geoip_build'
    _log 'On Debian 12/13, you may need to run: "%s"\n' "apt --mark-auto install libtext-csv-xs-perl"
    return 1
  }

  rm -f dbip-country-lite.csv || {
    _elog 'Failed to remove dbip-country-lite.csv now that it has been consumed.'
    return 1
  }

  _log 'GeoIP database is updated in /usr/share/xt_geoip'
  return 0
}

main "$@" || exit 1
exit 0
