#!/bin/sh

# The GPLv2 License
#
#   Copyright (C) 2025 pyamsoft
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

main() {
  if [ "$(id -u)" -ne 0 ]; then
    printf -- 'Must run as root.\n'
    return 1
  fi

  cd /usr/libexec/xtables-addons || {
    printf -- 'Failed to cd into xtables-addons directory.\n'
    return 1
  }

  mkdir -p /usr/share/xt_geoip || {
    printf -- 'Failed to make target xt_geoip directory.\n'
    return 1
  }

  chmod 755 /usr/share/xt_geoip || {
    printf -- 'Failed to mark exec target xt_geoip directory.\n'
    return 1
  }

  # Download (will save as dbip-country-lite.csv)
  ./xt_geoip_dl || {
    printf -- 'Failed to download latest geoip.\n'
    return 1
  }

  ./xt_geoip_build -D /usr/share/xt_geoip dbip-country-lite.csv || {
    printf -- 'Failed to convert CSV to GEO-IP\n'
    printf -- 'On Debian 12, you may need to run: "%s"\n' "apt --mark-auto install libtext-csv-xs-perl"
    return 1
  }

  rm -f dbip-country-lite.csv || {
    printf -- 'Failed to remove dbip-country-lite CSV\n'
    return 1
  }

  printf -- 'GeoIP database is updated in /usr/share/xt_geoip\n'
  return 0
}

main "$@" || exit 1
exit 0
